baseURL = 'http://blog.cristianoprogramador.com'
copyright = "{year}"
languageCode = 'pt-br'
defaultContentLanguage = 'pt'
theme = 'enchanted-lowkey'
title = 'Blog - Cristiano Raffi Cunha'
enableRobotsTXT = true
summaryLength = 15

[pagination]
  pagerSize = 5

[services]
  [services.disqus]
    shortname = 'http-blog-cristianoprogramador-com'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
